### ISSUE TITLE
Wait for phpstan to integrate/test `6.0.x` before releasing `6.0.0`

### ISSUE THREAD

**Issue by Ocramius** [Roave/BetterReflection#1232]
This is a signpost issue to prevent accidental `6.0.0` release.

We'll need @ondrejmirtes green light to 🚢

**Comment by ondrejmirtes** [comment]
Just to give you a small update - I've been working on this and testing since Monday, and finally I've got the green build. BR 6.0.x is in a good state.

The only thing I'd suggest to do is something similar to this - https://github.com/ondrejmirtes/BetterReflection/commit/8d0a0f63997397b24c270db00b3bf4071866844a. What it does is that parameters don't have to be recreated when calling with `withCurrentClass`. It'd only be necessary if parameters were allowed to use `static` type which they aren't. This commit saves around 20 % of memory consumption in PHPStan, around 110 MB. It results in around half of the ReflectionParameter instances being created so a lot less memory is leaking.

What I have left to do in order to close this issue:

1) I want to test that PHPStan issues around circular references in extends/implements are fixed.
2) I want to write some tests for PHP 8.2 features like readonly classes and DNF types.

I hope to greenlight 6.0.0 tomorrow after I do these steps :) Thanks.

**Comment by ondrejmirtes** [comment]
Alright, I greenlight BetterReflection 6.0.0, we're good to go :) Thank you very much.

It's up to you if you want to do the memory optimization inspired by https://github.com/ondrejmirtes/BetterReflection/commit/8d0a0f63997397b24c270db00b3bf4071866844a before release or decide it later in 6.x.

**Comment by Ocramius** [comment]
@kukulich I will cut a release tomorrow, unless you have more stuff you want in 6.0

**Comment by Ocramius** [comment]
Looks like a non-breaking change: can be done afterwards 👍

**Comment by kukulich** [comment]
`ReflectionMethod::getCurrentClass()` is in public API so it should not lie for `$parameter->getDeclaringFunction()->getCurrentClass()`.

However the optimization is nice and it can really make a difference because `ReflectionMethod::withCurrentClass()` is called in `ReflectionClass::getParentMethods()`.

Maybe we can do one last BC break and mark `ReflectionMethod::getCurrentClass()` as `@internal` ? I think it should be safe. The end user should have current class available just after the call `Reflector->reflectClass()`.

**Comment by Ocramius** [comment]
Marking it as `@internal` works :+1:

**Comment by Ocramius** [comment]
Closing here, thanks everyone!
