### ISSUE TITLE
Make Better Reflection faster

### ISSUE THREAD

**Issue by asgrim** [Roave/BetterReflection#131]
It's pretty slow. Benchmarking a simple `hasMethod` call vs `method_exists` and core reflection, just 1,000 iterations:

```
using method_exists... 0.0006260871887207 seconds.
using core reflection... 0.0013439655303955 seconds.
using better reflection... 7.447105884552 seconds.
```

Pretty pitiful performance if I do say so myself :chart_with_downwards_trend:

**Comment by Ocramius** [comment]
Not sure if it's relevant, tbh.

Reflection is usually to be avoided in runtime context, so I would rather benchmark it only for contexts where performance is actually relevant.

The only context where better reflection may be more interesting to use at runtime is AOP, and there it usually is cached (reflection happens only once, to see whether the file containing a class was changed)

**Comment by asgrim** [comment]
I think we can still do better than 7 seconds, but in my opinion this isn't a high priority thing. Also, I haven't actually had any thoughts on how to improve performance aside from caching stuff more. Additionally, I have no clue about the performance of PhpParser (it may be fast or that may be a bottleneck - if that is a bottleneck, we could compare the performance of the PHP 7 builtin AST parser, although this may mean rewriting a significant amount of internals already.

**Comment by Ocramius** [comment]
Profiling the benchmarks will give you a good overview

**Comment by asgrim** [comment]
Interesting; what sort of use case do you have that means you need to reflect so many items? In honestly, I've only used it in quite specific scenarios so far, so interested to hear what folks are doing with BR.

**Comment by kdambekalns** [comment]
Well, I use annotations to control exporting of "controllers" and domain models via OData. There is a bunch of classes in the system that need to be reflected for their properties and potentially exported methods. I checked, there are 81 model classes and around 80 other classes. Not really "a ton" of classes…

I even filter for a special annotation (using `strpos` on the source) before actually reflecting, but still it takes a lot of time. Unfortunately using the builtin reflection is not possible, due to some crappy code being in that system (where merely _loading_ a class has side-effects already, like actually _running_ some code)…

**Comment by Ocramius** [comment]
The only thing I can think of here is to add a caching layer in the source locators (`CachedSourceLocator`?), but then, not the scope of the lib, IMO.

**Comment by kukulich** [comment]
@Ocramius This can be closed I think, hmm?

**Comment by Ocramius** [comment]
Yup!

**Comment by Ocramius** [comment]
Ref: https://github.com/Roave/BetterReflection/pull/338
Ref: https://github.com/Roave/BetterReflection/pull/346

**Comment by kdambekalns** [comment]
Just for the record: I use native reflection now (the codebase I need this to work on improved to the point it became possible), and it's taking about a second now. The caching I added before still in place, so really fast now.

Thanks for this library anyway! :)
