### ISSUE TITLE
Incorrect exeptions with enums

### ISSUE THREAD

**Issue by SimonVorgers** [Roave/BetterReflection#1384]
I have a question related to this [MR](https://github.com/Roave/BetterReflection/pull/1380)

Can you tell us why this should throw an exception?

[File:](https://github.com/Roave/BetterReflection/blob/6.20.x/test/unit/NodeCompiler/CompileNodeToValueTest.php#L744)
  ```php
  enum Foo: int {
      case ONE = 1;
  }
  class Bat {
      const ONE_VALUE = Foo::ONE;
  }
```
Should be supported since php 8.1.0 :thinking: 
Because now, its throwing every time an exception.

[File:](https://github.com/Roave/BetterReflection/blob/6.20.x/src/NodeCompiler/CompileNodeToValue.php#L247C56-L247C56)
```php
if ($classReflection instanceof ReflectionEnum) {
  throw Exception\UnableToCompileNode::becauseOfValueIsEnum($context, $classReflection, $node);
}
```
The  comment from original [issue](https://github.com/Roave/BetterReflection/issues/1376#issue-1993210421) could also work.

Thanks in advance

**Comment by Ocramius** [comment]
>  this should throw an exception?

Static analysis should work, but retrieving the **value** of an ENUM is not possible, because ENUMs only exist as instances.

The core invariant of BetterReflection, which is what should make it "better", is that it shouldn't load any code: instantiating an ENUM will cause autoloading, which will already break this core design constraint that is the foundation of the entire library.

**Comment by Ocramius** [comment]
Closing: explained above
