### ISSUE TITLE
Creating an attribute instance from the ReflectionAttribute

### ISSUE THREAD

**Issue by jakubtobiasz** [Roave/BetterReflection#1456]
Hello,

maybe I'm blind or miss something, but it seems it's not possible to create an instance of an attribute from the reflection. Is it on purpose or it's a missing feature?

I'll be more than happy to open a PR for that, but before, I'd like to make sure it isn't on purpose.

**Comment by Ocramius** [comment]
This is correct, because it would lead to autoloading, which goes against the very core design of this Libra.

The one invariant that makes this library usable as it is is that it won't load your sources through the PHP engine.

You may be able to do such a thing with an adapter, with major warnings.
