### ISSUE TITLE
[question] Is the AST Tree cached?

### ISSUE THREAD

**Issue by aik099** [Roave/BetterReflection#1468]
When I call several of a `\Roave\BetterReflection\Reflector\DefaultReflector` class methods together (one after other), e.g. `reflectClass` and `reflectFunction` for the same file would the AST tree:

1. be built once and then reused for subsequent calls to the same file?
2. be built each time?

**Comment by Ocramius** [comment]
It's an implementation detail / shouldn't matter.

**Comment by aik099** [comment]
Performance-wise it matters. 

If AST tree building takes time (large PHP file) and it's rebuilt each time I try to reflect something new in the file that I've already reflected (using the `DefaultReflector` class instance I already have), then this is a performance issue.

**Comment by Ocramius** [comment]
Effectively, what you care about is how your source locator is built:

https://github.com/Roave/BetterReflection/blob/0f82edc5d371730e530de90a5e3ce4de576cbb7d/src/BetterReflection.php#L44-L48

In the context of the test suite of this project, we re-use a singleton `BetterReflection` instance, to re-use the memoization properties across all tests:

https://github.com/Roave/BetterReflection/blob/0f82edc5d371730e530de90a5e3ce4de576cbb7d/test/unit/BetterReflectionSingleton.php#L19

We can do this mostly due to the functional purity of `BetterReflection` though: this highly depends on the `SourceLocator` you want to use.

**Comment by aik099** [comment]
I understand now that wrapping the used source locator into the `MemoizingSourceLocator` source location will provide the caching layer I need.

Thank you.

**Comment by Ocramius** [comment]
Another very big consideration is that `AggregateSourceLocator` uses an iterative approach to finding sources: designing your source locator is very much akin designing your autoloader.

If your code does a `foreach (glob("*") ... )` (pseudo-code, at logical level), you are going to suffer a massive performance penalty.

We provide PSR-compatible source locator factories: https://github.com/Roave/BetterReflection/tree/0f82edc5d371730e530de90a5e3ce4de576cbb7d/src/SourceLocator/Type/Composer/Factory
