### ISSUE TITLE
Prepare 1.0.0 release notes

### ISSUE THREAD

**Issue by Ocramius** [Roave/BetterReflection#159]

**Comment by asgrim** [comment]
Total issues resolved: **19**
- [37: Add ability to create a ReflectionFunction from a closure](https://github.com/Roave/BetterReflection/issues/37)
- [61: Reflection* classes should be uncloneable](https://github.com/Roave/BetterReflection/issues/61)
- [87: Cannot determine default value for internal classes](https://github.com/Roave/BetterReflection/issues/87)
- [101: #87 Loads of stubs](https://github.com/Roave/BetterReflection/pull/101)
- [109: Variadic arguments are always optional](https://github.com/Roave/BetterReflection/issues/109)
- [114: Implement &#91;g|s&#92;etStaticPropertyValue in ReflectionClass](https://github.com/Roave/BetterReflection/pull/114)
- [130: Fetch AST or Code for a method/function](https://github.com/Roave/BetterReflection/issues/130)
- [133: Allow exporting a reflection to PHP](https://github.com/Roave/BetterReflection/issues/133)
- [135: Add returning AST methods](https://github.com/Roave/BetterReflection/pull/135)
- [145: Ability to create non-class/function reflections by Name](https://github.com/Roave/BetterReflection/issues/145)
- [147: Added demo folder](https://github.com/Roave/BetterReflection/pull/147)
- [149: Use branch-alias instead of dev-master](https://github.com/Roave/BetterReflection/pull/149)
- [150: Make reflections uncloneable](https://github.com/Roave/BetterReflection/pull/150)
- [151: Reflect from Closures](https://github.com/Roave/BetterReflection/pull/151)
- [153: Added functions for static initialisation](https://github.com/Roave/BetterReflection/pull/153)
- [156: Removed var&#95;dump to avoid spinning tests](https://github.com/Roave/BetterReflection/pull/156)
- [157: Make sure variadic arguments are always optional](https://github.com/Roave/BetterReflection/pull/157)
- [158: Run against lowest dependencies as well](https://github.com/Roave/BetterReflection/pull/158)
- [160: Updated require versions ready for 1.0.0 release](https://github.com/Roave/BetterReflection/pull/160)

**Comment by asgrim** [comment]
@Ocramius happy for me to tag it and release?

**Comment by Ocramius** [comment]
@asgrim :+1: 

Blogpost maybe?

**Comment by asgrim** [comment]
Okay, I'll knock something up first o_O

**Comment by asgrim** [comment]
http://jamestitcumb.com/posts/better-reflection-1.0.0
https://github.com/Roave/BetterReflection/releases/tag/1.0.0
