### ISSUE TITLE
Replace core Reflections with BetterReflection in ProxyManager

### ISSUE THREAD

**Issue by asgrim** [Roave/BetterReflection#39]
@Ocramius would like to use BetterReflection in https://github.com/Ocramius/ProxyManager. See if this is possible, and see what we need to do to make it compatible.

**Comment by Ocramius** [comment]
Good news about this: *ProxyManager* seems to (currently) only use the `new` operator for `ReflectionClass` in:

 - [`AbstractBaseFactory#generateProxy()`](https://github.com/Ocramius/ProxyManager/blob/7badedb5f8afaaccd496a096daadb19d7bf2b374/src/ProxyManager/Factory/AbstractBaseFactory.php#L90)
 - [`AbstractBaseFactory#generateProxyClass()`](https://github.com/Ocramius/ProxyManager/blob/7badedb5f8afaaccd496a096daadb19d7bf2b374/src/ProxyManager/Factory/AbstractBaseFactory.php#L115)

Clean code pays off! Injecting a reflector or a factory instead of using `ReflectionClass` directly would be sufficient once *BetterReflection* reaches API parity with PHP's Reflection

**Comment by asgrim** [comment]
Implementation has commenced in Ocramius/ProxyManager#243

**Comment by Ocramius** [comment]
Closing here, not related to the project directly.
