### ISSUE TITLE
How to patch class and save it back to the file?

### ISSUE THREAD

**Issue by funivan** [Roave/BetterReflection#432]
In this example: `monkey patching` https://github.com/Roave/BetterReflection/blob/master/demo/monkey-patching/index.php
we can change the body of the method. 
How to store changed code back to `MyClass.php`?

I know that we can use PrettyPrinter, but we need to pass whole file AST. And we have only class AST. Thanks for the help.

**Comment by asgrim** [comment]
Static modification isn't really an intended use case, so that's not possible at the moment. The intention is the modification is made, and the result is cached for the specific class only, when the class in question is autoloaded then we load our class instead of the original class... Note that Better Reflection is not really a code generation tool!

**Comment by funivan** [comment]
Thanks for the clarification.
