### ISSUE TITLE
Bump minimum required version to 7.4.1+

### ISSUE THREAD

**Issue by Ocramius** [Roave/BetterReflection#571]

**Comment by dereuromark** [comment]
For what reason?
There are many libraries that depend on a library that uses this one here. And those need to work still in php73 and some even php72. That would just prevent them from getting those bugfixes.

If there is no pressing reason it is always best for libraries to have a reasonable frame of versions supported.

**Comment by asgrim** [comment]
> For what reason?

The maintainers give their time and support for free, so if we feel we should bump the minimum PHP version, then we will :smile:  Remember, because this is open source software (see https://github.com/Roave/BetterReflection/blob/master/LICENSE for details), you are more than free to fork it and support your own fork which maintains compatibility with PHP 7.2 :heart: thanks!

**Comment by Ocramius** [comment]
Few reasons to be added:

 * we want to be able to use newer tooling (typed properties are a big one here)
 * we want to maintain smaller dependency ranges to ensure maximum stability for a certain target release
 * we want downstream to get the best possible version we can deliver, and we work to our best effort when we work with the tools that we consider to be best
 * we do this for fun in our free time: might as well use what we want to work with

**Comment by kukulich** [comment]
You can assign me to this.

**Comment by Ocramius** [comment]
@kukulich do we want to bump to 7.4.1+ with `4.3.0` or `4.4.0`? I would probably release `4.3.0` within today (with the current fixes) and then bump from there, if you agree

**Comment by kukulich** [comment]
@Ocramius I have the same idea so I agree to release 4.3.0 with current PHP requirement :)

@ondrejmirtes Do you have any unreported bugs? :)

**Comment by ondrejmirtes** [comment]
I plan to go through the commits to my fork and some classes I copied over to phpstan-src to see what remains.

1) This big one is still open: https://github.com/Roave/BetterReflection/issues/573

2) Another one (that I haven't reported yet) is that AutoloadSourceLocator doesn't support class aliases. This is how I initially implemented it: https://github.com/phpstan/phpstan-src/blob/c0cb3a69266d1530b5710016eb7eb471e03f9d02/src/Reflection/BetterReflection/SourceLocator/AutoloadSourceLocator.php I think it can no longer extend the abstract parent class. This part is important: https://github.com/phpstan/phpstan-src/commit/c0cb3a69266d1530b5710016eb7eb471e03f9d02#diff-b84fb81e70db3cdb6b4495c80b475a44R110-R123

3) One more thing that I recently did is that to match PHP behaviour, AutoloadSourceLocator also has to know about other symbols in an autoloaded file. Let's say that there's class A, function B and constant C in a file. If you ask for class A, PHP suddenly also knows about function B and constant C, which traditionally cannot be autoloaded, but PHP will know about them after class A is loaded. So what I'm doing is that AutoloadSourceLocator is memoizing all the found symbols in a file after reading it, and responds to them when asked about them later. It's a little bit undeterministic behaviour but I really wanted to match the behaviour 1:1. It's fine by me if you don't want it.

4) Another thing that @kukulich plans to tackle is to parse @since annotation and filter out stuff in the PhpStorm source stubber based on the given PHP version. But that can wait until later.

**Comment by Ocramius** [comment]
Could you please report those as separate issues? That way, we can at least get work started/more eyes on it (if needed)

**Comment by ondrejmirtes** [comment]
Yeah, of course, I now remembered a few more, mainly related to performance :)

**Comment by ondrejmirtes** [comment]
I've reported all the issues I currently know about :) There's a lot of them but they make BetterReflection work in PHPStan really well :)
