### ISSUE TITLE
PhpStormStubsSourceStubber can support filtering identifiers based on given PHP version

### ISSUE THREAD

**Issue by kukulich** [Roave/BetterReflection#603]
Based on `@since` annotations

Eg. https://github.com/JetBrains/phpstorm-stubs/blob/master/FFI/FFI.php#L17

**Comment by ondrejmirtes** [comment]
A few cases are tricky to handle:

* `array_push` has `@since 7.3` but it's also in older versions.
* `setcookie` is present multiple times which causes it to be overriden in a single-dimension array.
* `CompileError` is available since PHP 7.3, but in the stubs there's `ParseError extends CompileError` which is available since PHP 7.0. I lie about this in my fork and make CompileError available since 7.0 too.

**Comment by kukulich** [comment]
Implemented in https://github.com/Roave/BetterReflection/pull/798
